annotations:
  category: Infrastructure
apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: A fully functional local AWS cloud stack
icon: https://github.com/localstack/localstack/raw/master/localstack/dashboard/web/img/localstack.png
keywords:
- aws
- localstack
maintainers:
- email: waldemar.hummer@gmail.com
  name: Waldemar Hummer
name: localstack
sources:
- https://localstack.cloud/
- https://github.com/localstack/localstack
type: application
version: 0.2.1
